/**:
  ros__parameters:
    maps_dir: /maps
    frame_id: map
    map_topic: /map

    docker_manager:
      service: /docker_manager/control_container
      events: /docker_manager/events

      # when loading a map we start all docker container with label [label]=active
      #   and stop all containers with [label]=inactive
      #
      # when unloading we start all docker container with label [label]=inactive
      #   and stop all containers with [label]=active
      label: env_manager


    map_server:
      frame_id: map
      topic_name: map

    map_saver:
      map_topic: /map
      image_format: pgm
      map_mode: trinary
      free_thresh: 0.25
      occupied_thresh: 0.65

    amcl:
      alpha1: 0.05 
      alpha2: 0.25 #0.2
      alpha3: 0.25 #0.2
      alpha4: 0.05
      alpha5: 0.2
      always_reset_initial_pose: false
      base_frame_id: "base_footprint"
      beam_skip_distance: 0.5
      beam_skip_error_threshold: 0.9
      beam_skip_threshold: 0.3
      do_beamskip: false
      first_map_only: false
      introspection_mode: "disabled"
      lambda_short: 0.1
      laser_likelihood_max_dist: 2.0
      laser_max_range: -1.0
      laser_min_range: -1.0
      laser_model_type: "likelihood_field"
      max_beams: 60
      max_particles: 4000 #5000
      min_particles: 800 #500
      odom_frame_id: "odom"
      pf_err: 0.05
      pf_z: 0.99
      recovery_alpha_fast: 0.0
      recovery_alpha_slow: 0.0
      resample_interval: 1
      robot_model_type: "nav2_amcl::DifferentialMotionModel"
      save_pose_rate: 0.5
      scan_topic: /scan_raw
      set_initial_pose: false
      sigma_hit: 0.2
      tf_broadcast: true
      transform_tolerance: 1.0
      update_min_a: 0.2
      update_min_d: 0.1
      z_hit: 0.5
      z_max: 0.05
      z_rand: 0.5
      z_short: 0.05
      set_initial_pose: true
      initial_pose:
        x: 0.0
        y: 0.0
        z: 0.0
        yaw: 0.0
