description: ''
joints:
- head_1_joint
- head_2_joint
key: head_sweep
name: head_sweep
positions:
- 0.0
- 0.0
- 1.0
- 0.0
- 0.0
- 0.0
- -1.0
- 0.0
- 0.0
- 0.0
times_from_start:
- 0.0
- 2.5
- 5.0
- 7.5
- 10.0
usage: ''
