/**:
  ros__parameters:
    camera_name: 'gemini'
    namespace: ''
    serial_number: 'CP086410006H'

    usb_port: ''
    device_num: 3
    uvc_backend: 'libuvc'  # libuvc or v4l2

    sync_mode: 'standalone'
    enable_d2c_viewer: false
    enable_ldp: true
    ordered_pc: false
    enable_depth_scale: true
    align_mode: 'SW'
    laser_energy_level: -1
    enable_heartbeat: false
    time_domain: 'global'

    depth_registration: true
    enable_point_cloud: true
    enable_colored_point_cloud: true
    cloud_frame_id: ''
    point_cloud_qos: 'default'
    connection_delay: 10

    color_width: 0
    color_height: 0
    color_fps: 0
    color_format: 'ANY'
    enable_color: true
    color_qos: 'default'
    color_camera_info_qos: 'default'
    enable_color_auto_exposure_priority: false
    color_rotation: -1  # 0, 90, 180, 270
    color_flip: false
    color_mirror: false
    color_ae_roi_left: -1
    color_ae_roi_left: -1
    color_ae_roi_right: -1
    color_ae_roi_top: -1
    color_ae_roi_bottom: -1
    color_exposure: -1
    color_gain: -1
    enable_color_auto_white_balance: true
    color_white_balance: -1
    enable_color_auto_exposure: true
    color_ae_max_exposure: -1
    color_brightness: -1
    color_sharpness: -1
    color_gamma: -1
    color_saturation: -1
    color_constrast: -1
    color_hue: -1
    enable_color_backlight_compenstation: false
    color_powerline_freq: ''  # disable ,50hz ,60hz ,auto
    enable_color_decimation_filter: false
    color_decimation_filter_scale: -1

    depth_width: 0
    depth_height: 0
    depth_fps: 0
    depth_format: 'ANY'
    enable_depth: true
    depth_qos: 'default'
    depth_camera_info_qos: 'default'
    enable_depth_auto_exposure_priority: false
    depth_precision: ''
    depth_rotation: -1  # 0, 90, 180, 270
    depth_flip: false
    depth_mirror: false
    depth_ae_roi_left: -1
    depth_ae_roi_right: -1
    depth_ae_roi_top: -1
    depth_ae_roi_bottom: -1
    mean_intensity_set_point: -1

    left_ir_width: 0
    left_ir_height: 0
    left_ir_fps: 0
    left_ir_format: 'ANY'
    enable_left_ir: false
    left_ir_qos: 'default'
    left_ir_camera_info_qos: 'default'
    left_ir_rotation: -1  # 0, 90, 180, 270
    left_ir_flip: false
    left_ir_mirror: false
    enable_left_ir_sequence_id_filter: false
    left_ir_sequence_id_filter_id: -1
    right_ir_width: 0
    right_ir_height: 0
    right_ir_fps: 0
    right_ir_format: 'ANY'
    enable_right_ir: false
    right_ir_qos: 'default'
    right_ir_camera_info_qos: 'default'
    right_ir_rotation: -1  # 0, 90, 180, 270
    right_ir_flip: false
    right_ir_mirror: false
    enable_right_ir_sequence_id_filter: false
    right_ir_sequence_id_filter_id: -1
    enable_ir_auto_exposure: true
    ir_exposure: -1
    ir_gain: -1
    ir_ae_max_exposure: -1
    ir_brightness: -1

    enable_sync_output_accel_gyro: false
    enable_accel: false
    enable_accel_data_correction: true
    accel_rate: '200hz'
    accel_range: '4g'
    enable_gyro: false
    enable_gyro_data_correction: true
    gyro_rate: '200hz'
    gyro_range: '1000dps'

    liner_accel_cov: 0.01
    angular_vel_cov: 0.01
    publish_tf: false
    tf_publish_rate: 0.0
    ir_info_url: ''
    color_info_url: ''
    enumerate_net_device: true
    net_device_ip: ''
    net_device_port: 0
    exposure_range_mode: 'default'
    log_level: 'none'
    enable_publish_extrinsic: false
    disaparity_to_depth_mode: 'HW'
    ldp_power_level: -1

    depth_delay_us: 0
    color_delay_us: 0
    trigger2image_delay_us: 0
    trigger_out_delay_us: 0
    trigger_out_enabled: true
    software_trigger_enabled: true
    frames_per_trigger: 2
    software_trigger_period: 33
    enable_ptp_config: false
    enable_frame_sync: true
    enable_decimation_filter: false
    enable_hdr_merge: false
    enable_sequence_id_filter: false
    enable_threshold_filter: false
    enable_hardware_noise_removal_filter: false
    enable_noise_removal_filter: true
    enable_spatial_filter: false
    enable_temporal_filter: false
    enable_disaparity_to_depth: true
    enable_hole_filling_filter: false
    enable_spatial_fast_filter: false
    enable_spatial_moderate_filter: false
    decimation_filter_scale: -1
    sequence_id_filter_id: -1
    threshold_filter_max: -1
    threshold_filter_min: -1
    hardware_noise_removal_filter_threshold: -1.0
    noise_removal_filter_min_diff: 256
    noise_removal_filter_max_size: 80
    spatial_filter_alpha: -1.0
    spatial_filter_diff_threshold: -1
    spatial_filter_magnitude: -1
    spatial_filter_radius: -1
    temporal_filter_diff_threshold: -1.0
    temporal_filter_weight: -1.0
    hole_filling_filter_mode: ''
    hdr_merge_exposure_1: -1
    hdr_merge_gain_1: -1
    hdr_merge_exposure_2: -1
    hdr_merge_gain_2: -1
    spatial_fast_filter_radius: -1
    spatial_moderate_filter_diff_threshold: -1
    spatial_moderate_filter_magnitude: -1
    spatial_moderate_filter_radius: -1
    align_target_stream: 'COLOR'
    diagnostic_period: 1.0
    enable_laser: true
    depth_precision: ''
    device_preset: 'Default'
    retry_on_usb3_detection_failure: false
    enable_sync_host_time: true
    enable_color_undistortion: false
    config_file_path: ''
    gmsl_trigger_fps: 3000
    enable_gmsl_trigger: false
    disparity_range_mode: -1
    disparity_search_offset: -1
    disparity_offset_config: false
    offset_index0: -1
    offset_index1: -1
    frame_aggregate_mode: 'ANY'
    interleave_ae_mode: 'laser'
    interleave_frame_enable: false
    interleave_skip_enable: false
    interleave_skip_index: 1

    hdr_index1_laser_control: 1
    hdr_index1_depth_exposure: 1
    hdr_index1_depth_gain: 16
    hdr_index1_ir_brightness: 20
    hdr_index1_ir_ae_max_exposure: 2000
    hdr_index0_laser_control: 1
    hdr_index0_depth_exposure: 7500
    hdr_index0_depth_gain: 16
    hdr_index0_ir_brightness: 60
    hdr_index0_ir_ae_max_exposure: 10000

    laser_index1_laser_control: 0
    laser_index1_depth_exposure: 3000
    laser_index1_depth_gain: 16
    laser_index1_ir_brightness: 60
    laser_index1_ir_ae_max_exposure: 17000
    laser_index0_laser_control: 1
    laser_index0_depth_exposure: 3000
    laser_index0_depth_gain: 16
    laser_index0_ir_brightness: 60
    laser_index0_ir_ae_max_exposure: 30000
    show_fps_enable: false

    upgrade_firmware: ''
    preset_firmware_path: ''
    load_config_json_file_path: ''
    export_config_json_file_path: ''