/pal_laser_filters:
  ros__parameters:
    /bond_disable_heartbeat_timeout: true
    filter1:
      name: range
      params:
        lower_replacement_value: -.inf
        lower_threshold: 0.0
        upper_replacement_value: .inf
        upper_threshold: 25.0
        use_message_range_limits: false
      type: laser_filters/LaserScanRangeFilter
    filter2:
      name: footprint_filter
      params:
        base_frame_id: ''
        footprint_type: ''
        inscribed_radius: 0.275
      type: pal_laser_filters/LaserScanFootprintFilter
    filter3:
      name: median
      type: laser_filters/LaserArrayFilter
      params:
        range_filter_chain:
          filter1:
            name: median
            type: filters/MultiChannelMedianFilterFloat
            params:
              number_of_observations: 5
              unused: 69
        intensity_filter_chain:
          filter1:
            name: median
            type: filters/MultiChannelMedianFilterFloat
            params:
              number_of_observations: 5
              unused: 69
    # filter3:
    #   name: shadow_filter
    #   type: laser_filters/ScanShadowsFilter
    #   params:
    #     min_angle: 10.
    #     max_angle: 100.
    #     neighbors: 5
    #     window: 1
    #     remove_shadow_start_point: true
    #     remove_shadow_end_point: true
    filter4:
      name: speckle_filter
      type: laser_filters/LaserScanSpeckleFilter
      params:
        # Select which filter type to use.
        # 0: Range based filtering (distance between consecutive points)
        # 1: Euclidean filtering based on radius outlier search
        filter_type: 0

        # Only ranges smaller than this range are taken into account
        max_range: 4.0 #2.0

        # filter_type[0] (Distance): max distance between consecutive points
        # filter_type[1] (RadiusOutlier): max distance between points
        max_range_difference: 0.05 #0.1

        # filter_type[0] (Distance): Number of consecutive ranges that will be tested for max_distance
        # filter_type[1] (RadiusOutlier): Minimum number of neighbors
        filter_window: 2 #2

    input_topic: scan_raw
    output_topic: scan
    use_sim_time: false

