iki_robot_node:
  ros__parameters:
    name: tiago
    modules:
      ObjectRecognitionModule: ""
      GraspPoseDetectionModule: /grasp_pose_detection
      MoveitWrapperModule: /moveit_wrapper
      DBModule: /tiago/core/file_server
      STTModule: /stt
      TTSModule: /tts
      UIModule:
        ask_for_confirmation: /ask_for_confirmation
      TraceModule: /traces/multi
      ChatModule:
        base_url: "http://192.168.66.68:8000/v1"
        model: "qwen3.5-122b-a10b"
      ImageModule:
        head:
          topic: /femto_mega/color/image_raw/compressed
          transport: compressed
        head_depth:
          topic: /femto_mega/depth/image_raw
          cv_encoding: 16UC1
          # From datasheet: https://d1cd332k3pgc17.cloudfront.net/wp-content/uploads/2023/04/ORBBEC_Datasheet_Femto-Mega1.pdf
          # With camera set to: NFOV Unbinned
          depth_min: 500 # mm (0.5m)
          depth_max: 3860 # mm (3.86m)
        floor: /head_front_camera/rgb/image_raw
        floor_depth:
          topic: /head_front_camera/depth/image_raw
          cv_encoding: 16UC1
          # From datasheet: https://cdn-reichelt.de/documents/datenblatt/C300/ORBBEC_ASTRA.pdf
          # Max depth is 5.0m, but here we limit it to 2.0m
          depth_min: 600 # mm (0.6m)
          depth_max: 2000 # mm (2.0m)
      NavModule:
        action_topic: /navigate_to_pose
        behavior_tree: ""
      #ParamsModule:
      #  controller_server:
      #    max_vel:
      #      x: /controller_server:FollowPath.max_vel_x
      #      y: /controller_server:FollowPath.max_vel_y
      #      theta: /controller_server:FollowPath.max_vel_theta
      #    min_vel:
      #      x: /controller_server:FollowPath.min_vel_x
      #      y: /controller_server:FollowPath.min_vel_y
      DockerModule: /docker_manager
      TriggerModule:
        is_door_open: /tiago/core/open_door_detector/is_door_open
        enter_arena: /enter_the_arena/enter
        wait_for_gripper_force: /wait_for_force
      PointHeadModule:
        action_topic: /head_controller/point_head
        pointing_frame: head_2_link
        pointing_axis: [1.0, 0.0, 0.0]
        min_duration: 1.0 # seconds
        max_velocity: 0.5 # rad/s
      TFModule: base_footprint
      PlayMotionModule:
        action_topic: /play_motion2
        list_motions_service: /play_motion2/list_motions
      ServiceModule:
        get_global_costmap: /global_costmap/get_costmap [nav2_msgs/srv/GetCostmap]
        clear_global_costmap: /global_costmap/clear_entirely_global_costmap [nav2_msgs/srv/ClearEntireCostmap]
        clear_local_costmap: /local_costmap/clear_entirely_local_costmap [nav2_msgs/srv/ClearEntireCostmap]
        start_perception: /grasp_pose_detection/start_perception [grasp_pose_detection_interfaces/srv/StartPerception]
      ActionModule:
        spin: /spin [nav2_msgs/action/Spin]
      WaypointModule: /waypoint_server
      VoconModule:
        asr_action: /vocon/ASR
        set_context_service: /vocon/set_context
      FollowPersonModule:
        action_topic: "/follow_person"
      LedManagerModule:
        color_topic:       "/mm11/led/set_strip_color"
        pixel_color_topic: "/mm11/led/set_strip_pixel_color"
        flash_topic:       "/mm11/led/set_strip_flash"
        animation_topic:   "/mm11/led/set_strip_animation"

