iki_robot_node:
  ros__parameters:
    name: tiago_sim
    modules:
      ObjectRecognitionModule: ""
      GraspPoseDetectionModule: /tiago/core/grasp_pose_detection
      MoveitWrapperModule: /moveit_wrapper
      DBModule: /tiago/core/file_server
      TTSModule: /tts
      STTModule: /stt
      UIModule:
        ask_for_confirmation: /ask_for_confirmation
      ChatModule:
        base_url: "http://192.168.1.166:8083/v1"
        model: "Qwen3.5-122B-A10B-MXFP4_MOE-00001-of-00003.gguf"
      NavModule:
        action_topic: /navigate_to_pose
        behavior_tree: ""
      ParamsModule:
        controller_server:
          max_vel:
            x: /controller_server:FollowPath.max_vel_x
            y: /controller_server:FollowPath.max_vel_y
            theta: /controller_server:FollowPath.max_vel_theta
          min_vel:
            x: /controller_server:FollowPath.min_vel_x
            y: /controller_server:FollowPath.min_vel_y
      DockerModule: /docker_manager
      TriggerModule:
        is_door_open: /tiago/core/open_door_detector/is_door_open
        enter_arena: /enter_the_arena/enter
        wait_for_gripper_force: /wait_for_force
      PointHeadModule:
        action_topic: /head_controller/point_head
        pointing_frame: head_2_link
        pointing_axis: [1.0, 0.0, 0.0]
        min_duration: 1.0 # seconds
        max_velocity: 0.5 # rad/s
      TFModule: base_footprint
      PlayMotionModule:
        action_topic: /play_motion2
        list_motions_service: /play_motion2/list_motions
      ServiceModule:
        get_global_costmap: /global_costmap/get_costmap [nav2_msgs/srv/GetCostmap]
        clear_global_costmap: /global_costmap/clear_entirely_global_costmap [nav2_msgs/srv/ClearEntireCostmap]
        clear_local_costmap: /local_costmap/clear_entirely_local_costmap [nav2_msgs/srv/ClearEntireCostmap]
        start_perception: /tiago/core/grasp_pose_detection/start_perception [grasp_pose_detection_interfaces/srv/StartPerception]
      ActionModule:
        spin: /spin [nav2_msgs/action/Spin]
      WaypointModule: /waypoint_server
      VoconModule:
        asr_action: /vocon/ASR
        set_context_service: /vocon/set_context
      ImageModule:
        head: /femto_mega/rgb/image_raw
        floor: /head_front_camera/rgb/image_raw
      FollowPersonModule:
        action_topic: "/follow_person"